const { app, BrowserWindow, globalShortcut, screen, ipcMain, Tray, Menu, nativeImage, shell, session } = require('electron');
const path = require('path');
const fs = require('fs');
const { spawn, execSync } = require('child_process');

// Set official app name & AppUserModelID for Windows OS protocol prompts & notifications
app.setName('Adyber AI');
if (process.platform === 'win32') {
  app.setAppUserModelId('com.adyber.app');
}

// Register custom protocol so browser can deep-link back to the app (adyber://)
if (process.defaultApp) {
  if (process.argv.length >= 2) {
    app.setAsDefaultProtocolClient('adyber', process.execPath, [path.resolve(process.argv[1])]);
  }
} else {
  app.setAsDefaultProtocolClient('adyber');
}

// Electron flags for WebGL & Audio performance
app.commandLine.appendSwitch('disable-gpu-shader-disk-cache');
app.commandLine.appendSwitch('disable-software-rasterizer');
app.commandLine.appendSwitch('enable-features', 'WebSpeech,AudioServiceLaunchOnStartup');
app.commandLine.appendSwitch('disable-features', 'AudioServiceSandbox');
app.commandLine.appendSwitch('use-fake-ui-for-media-stream', 'false');

let mainWindow = null;
let tray = null;

// Module-scoped process handle so stopPythonBackend is accessible in will-quit
let pyProcess = null;

function stopPythonBackend() {
  if (pyProcess) {
    try { pyProcess.kill(); } catch (e) {}
    pyProcess = null;
  }
}

function createWindow() {
  const primaryDisplay = screen.getPrimaryDisplay();
  const { width: screenWidth } = primaryDisplay.workAreaSize;

  const windowWidth = 1200;
  const windowHeight = 700;

  mainWindow = new BrowserWindow({
    width: windowWidth,
    height: windowHeight,
    x: Math.floor((screenWidth - windowWidth) / 2),
    y: Math.floor((primaryDisplay.workAreaSize.height - windowHeight) / 2),
    frame: false,
    transparent: true,
    backgroundColor: '#00000000',
    hasShadow: false,
    alwaysOnTop: false,
    resizable: true,
    skipTaskbar: false,
    icon: path.join(__dirname, '../public/logo.png'),
    show: false,
    webPreferences: {
      preload: path.join(__dirname, 'preload.cjs'),
      nodeIntegration: false,
      contextIsolation: true,
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36'
    }
  });

  mainWindow.once('ready-to-show', () => {
    mainWindow.show();
  });

  Menu.setApplicationMenu(null);
  mainWindow.setMenu(null);

  ipcMain.on('wake-up', () => {
    if (mainWindow) {
      mainWindow.setAlwaysOnTop(true, 'screen-saver');
      mainWindow.showInactive();
    }
  });

  function startPythonBackend() {
    const appDataFolder = path.join(process.env.APPDATA || path.join(process.env.HOME || '', 'AppData', 'Roaming'), 'AdyberAI');
    try { fs.mkdirSync(appDataFolder, { recursive: true }); } catch (e) {}

    const tokenPath1 = path.join(appDataFolder, '.api_token');
    const tokenPath2 = app.isPackaged
      ? path.join(process.resourcesPath, 'adyber-backend/.api_token')
      : path.join(__dirname, '../backend/.api_token');

    // Remove stale token file so frontend waits for fresh token generated by new backend process
    try { if (fs.existsSync(tokenPath1)) fs.unlinkSync(tokenPath1); } catch (e) {}
    try { if (fs.existsSync(tokenPath2)) fs.unlinkSync(tokenPath2); } catch (e) {}

    const logFile = path.join(appDataFolder, 'backend.log');
    const logStream = fs.createWriteStream(logFile, { flags: 'w' });

    let pyCmd = '';
    let pyArgs = [];
    let cwd = '';

    if (app.isPackaged) {
      // In production built package, run compiled standalone binary executable
      const standaloneExe = path.join(process.resourcesPath, 'adyber-backend', 'adyber-backend.exe');
      pyCmd = standaloneExe;
      pyArgs = [];
      cwd = path.join(process.resourcesPath, 'adyber-backend');
    } else {
      // In dev mode, run python backend/server.py directly
      cwd = path.join(__dirname, '..');
      const backendServerPath = path.join(__dirname, '../backend/server.py');
      if (process.platform === 'win32') {
        try {
          execSync('py -3 --version', { stdio: 'ignore' });
          pyCmd = 'py';
          pyArgs = ['-3', backendServerPath];
        } catch (e) {
          pyCmd = 'python';
          pyArgs = [backendServerPath];
        }
      } else {
        pyCmd = 'python3';
        pyArgs = [backendServerPath];
      }
    }

    const logMsg = `[${new Date().toISOString()}] Spawning Backend (Packaged=${app.isPackaged}): ${pyCmd} ${pyArgs.join(' ')}\nCWD: ${cwd}\n`;
    console.log(logMsg);
    logStream.write(logMsg);

    try {
      pyProcess = spawn(pyCmd, pyArgs, {
        cwd: cwd,
        env: {
          ...process.env,
          PYTHONUNBUFFERED: '1',
          PYTHONPATH: `${cwd};${path.join(cwd, 'backend')};${process.env.PYTHONPATH || ''}`
        }
      });

      pyProcess.stdout?.on('data', (data) => {
        const text = data.toString();
        console.log(`[Python stdout]: ${text.trim()}`);
        logStream.write(`[STDOUT] ${text}`);
      });

      pyProcess.stderr?.on('data', (data) => {
        const text = data.toString();
        console.error(`[Python stderr]: ${text.trim()}`);
        logStream.write(`[STDERR] ${text}`);
      });

      pyProcess.on('error', (err) => {
        const errText = `[Python spawn error]: ${err.stack || err.message}\n`;
        console.error(errText);
        logStream.write(errText);
      });

      pyProcess.on('exit', (code) => {
        const exitMsg = `[Python process exited] code: ${code}\n`;
        console.log(exitMsg);
        logStream.write(exitMsg);
        pyProcess = null;
      });
    } catch (e) {
      const catchText = `[Python start exception]: ${e.stack || e.message}\n`;
      console.error(catchText);
      logStream.write(catchText);
    }
  }

  startPythonBackend();

  ipcMain.handle('get-api-token', async () => {
    const appDataFolder = path.join(process.env.APPDATA || path.join(process.env.HOME || '', 'AppData', 'Roaming'), 'AdyberAI');
    const tokenPath1 = path.join(appDataFolder, '.api_token');
    const tokenPath2 = app.isPackaged
      ? path.join(process.resourcesPath, 'backend/.api_token')
      : path.join(__dirname, '../backend/.api_token');

    try {
      // Retry reading for up to 10 seconds in case backend is slow to start
      for (let i = 0; i < 20; i++) {
        if (fs.existsSync(tokenPath1)) {
          return fs.readFileSync(tokenPath1, 'utf-8').trim();
        }
        if (fs.existsSync(tokenPath2)) {
          return fs.readFileSync(tokenPath2, 'utf-8').trim();
        }
        await new Promise(resolve => setTimeout(resolve, 500));
      }
    } catch(e) {
      console.error("[Auth] Failed to read .api_token:", e);
    }
    return "";
  });

  // --- DYNAMIC WINDOW RESIZING (IPC) ---
  ipcMain.on('window-onboarding', () => {
    if (mainWindow) {
      mainWindow.setMinimumSize(800, 500);
      mainWindow.setSize(1200, 700);
      mainWindow.center();
      mainWindow.setResizable(true);
      mainWindow.setAlwaysOnTop(false);
      mainWindow.setSkipTaskbar(false);
    }
  });

  ipcMain.on('window-orb', () => {
    if (mainWindow) {
      mainWindow.setResizable(false);
      mainWindow.setMinimumSize(260, 120);
      mainWindow.setSize(260, 120);
      mainWindow.setPosition(Math.floor((screenWidth - 260) / 2), 16);
      mainWindow.setAlwaysOnTop(true, 'screen-saver');
      mainWindow.setSkipTaskbar(true);
      mainWindow.show();
    }
  });

  ipcMain.on('window-hide', () => {
    if (mainWindow) mainWindow.hide();
  });

  ipcMain.on('window-minimize', () => {
    if (mainWindow) {
      mainWindow.setSkipTaskbar(false);
      mainWindow.minimize();
    }
  });

  ipcMain.on('window-maximize', () => {
    if (mainWindow) {
      if (mainWindow.isMaximized()) mainWindow.unmaximize();
      else mainWindow.maximize();
    }
  });

  ipcMain.on('window-resize', (_event, width, height) => {
    if (mainWindow) {
      const w = Math.max(200, Math.min(width, 1600));
      const h = Math.max(100, Math.min(height, 1200));
      mainWindow.setSize(w, h);
    }
  });

  const blockableOSShortcuts = ['CommandOrControl+Space', 'Alt+Space', 'CommandOrControl+Alt+Space', 'Shift+Space'];

  ipcMain.on('start-recording', () => {
    blockableOSShortcuts.forEach(sc => {
      try {
        globalShortcut.register(sc, () => {
          if (mainWindow) {
            let modifiers = [];
            if (sc.includes('CommandOrControl')) modifiers.push('ctrl');
            if (sc.includes('Alt')) modifiers.push('alt');
            if (sc.includes('Shift')) modifiers.push('shift');
            
            mainWindow.webContents.sendInputEvent({ type: 'keyDown', keyCode: 'Space', modifiers: modifiers });
            setTimeout(() => {
              if (mainWindow && !mainWindow.isDestroyed()) {
                mainWindow.webContents.sendInputEvent({ type: 'keyUp', keyCode: 'Space', modifiers: modifiers });
              }
            }, 100);
          }
        });
      } catch(e) {}
    });
  });

  ipcMain.on('stop-recording', () => {
    blockableOSShortcuts.forEach(sc => {
      try { globalShortcut.unregister(sc); } catch(e) {}
    });
  });

  ipcMain.on('clear-app-session', async () => {
    try {
      if (session.defaultSession) {
        await session.defaultSession.clearStorageData({
          storages: ['appcache', 'cookies', 'localstorage', 'indexdb', 'websql', 'serviceworkers', 'cachestorage']
        });
        console.log("[Electron Main] Successfully wiped all app storage data from disk on logout.");
      }
    } catch(err) {
      console.error("[Electron Main] Failed to clear app session storage data:", err);
    }
  });

  // IPC: open system browser for Google auth
  const http = require('http');
  const crypto = require('crypto');
  let authCallbackServer = null;
  let expectedAuthState = null;

  ipcMain.on('start-browser-auth', () => {
    // Kill any previous server
    if (authCallbackServer) {
      try { authCallbackServer.close(); } catch(e) {}
      authCallbackServer = null;
    }

    expectedAuthState = crypto.randomBytes(16).toString('hex');
    const port = 54321;

    // Spin up local callback receiver
    authCallbackServer = http.createServer((req, res) => {
      res.setHeader('Access-Control-Allow-Origin', '*');
      res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
      res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

      if (req.method === 'OPTIONS') { res.writeHead(204); res.end(); return; }

      if (req.url === '/callback' && req.method === 'POST') {
        let body = '';
        req.on('data', c => { body += c; });
        req.on('end', () => {
          try {
            const userData = JSON.parse(body);
            // Verify state nonce to prevent local SSRF / CSRF login spoofing
            if (!userData.state || userData.state !== expectedAuthState) {
              res.writeHead(401); res.end('Unauthorized callback');
              return;
            }
            expectedAuthState = null; // consume nonce

            if (mainWindow) {
              mainWindow.webContents.send('google-auth-success', userData);
              if (mainWindow.isMinimized()) mainWindow.restore();
              mainWindow.show();
              mainWindow.focus();
            }
            res.writeHead(200, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({ ok: true }));
          } catch(e) {
            res.writeHead(400); res.end('Bad request');
          }
          setTimeout(() => {
            if (authCallbackServer) {
              try { authCallbackServer.close(); } catch(err) {}
              authCallbackServer = null;
            }
          }, 2000);
        });
      } else {
        res.writeHead(404); res.end();
      }
    });

    authCallbackServer.listen(port, '127.0.0.1', () => {
      const authPageUrl = `https://adyber-d615d.firebaseapp.com/auth.html?state=${expectedAuthState}`;
      shell.openExternal(authPageUrl);
    });
  });

  ipcMain.on('window-close', () => {
    if (mainWindow) mainWindow.hide();
  });

  mainWindow.webContents.session.setPermissionRequestHandler((webContents, permission, callback) => {
    if (permission === 'media' || permission === 'microphone' || permission === 'audioCapture') {
      callback(true);
    } else {
      callback(false);
    }
  });

  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    // Allow Firebase Auth & Google OAuth popups inside Electron child windows
    if (
      url.includes('firebaseapp.com') ||
      url.includes('accounts.google.com') ||
      url.includes('google.com/o/oauth2') ||
      url.includes('google.com/signin')
    ) {
      return {
        action: 'allow',
        overrideBrowserWindowOptions: {
          autoHideMenuBar: true,
          webPreferences: {
            nodeIntegration: false,
            contextIsolation: true,
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36'
          }
        }
      };
    }

    if (url.startsWith('http:') || url.startsWith('https:')) {
      shell.openExternal(url);
      return { action: 'deny' };
    }
    return { action: 'allow' };
  });

  mainWindow.webContents.session.setPermissionCheckHandler((webContents, permission) => {
    if (permission === 'media' || permission === 'microphone' || permission === 'audioCapture') {
      return true;
    }
    return false;
  });

  const isDev = !app.isPackaged;
  if (isDev) {
    const devUrl = 'http://localhost:5173';
    const loadDev = () => {
      mainWindow.loadURL(devUrl).catch(() => {
        setTimeout(loadDev, 300);
      });
    };
    loadDev();
  } else {
    mainWindow.loadFile(path.join(__dirname, '../dist/index.html'));
  }

  // Let Python's GetAsyncKeyState kernel listener handle hotkeys to avoid OS keystroke swallowing.
}

// Handle deep-link callback from system browser: adyber://callback?user=BASE64
function handleProtocolUrl(urlStr) {
  try {
    if (!urlStr || !urlStr.startsWith('adyber://')) return;
    const httpUrl = urlStr.replace(/^adyber:\/\//, 'http://localhost/');
    const parsed = new URL(httpUrl);
    const userParam = parsed.searchParams.get('user') || parsed.searchParams.get('data');
    if (userParam && mainWindow) {
      let userDataStr = '';
      try {
        userDataStr = Buffer.from(decodeURIComponent(userParam), 'base64').toString('utf8');
      } catch(e) {
        userDataStr = decodeURIComponent(userParam);
      }
      const userData = JSON.parse(userDataStr);
      console.log("[Auth Protocol] Received user auth via adyber:// deep link:", userData.email);

      mainWindow.webContents.send('google-auth-success', userData);
      if (mainWindow.isMinimized()) mainWindow.restore();
      mainWindow.show();
      mainWindow.focus();
    }
  } catch(e) {
    console.error('[Protocol] Error parsing adyber:// URL:', e);
  }
}

const gotTheLock = app.requestSingleInstanceLock();
if (!gotTheLock) {
  app.quit();
} else {
  app.on('second-instance', (_event, commandLine) => {
    const url = commandLine.find(arg => arg.startsWith('adyber://'));
    if (url) handleProtocolUrl(url);
    if (mainWindow) {
      if (mainWindow.isMinimized()) mainWindow.restore();
      mainWindow.show();
      mainWindow.focus();
    }
  });
}

app.whenReady().then(() => {
  createWindow();

  // Handle protocol on macOS
  app.on('open-url', (_event, url) => {
    handleProtocolUrl(url);
  });

  const iconPath = path.join(__dirname, '../public/logo.png');
  const icon = nativeImage.createFromPath(iconPath).resize({ width: 16, height: 16 });
  tray = new Tray(icon);
  tray.setToolTip('Adyber AI');
  
  const contextMenu = Menu.buildFromTemplate([
    { 
      label: 'Open Adyber Dashboard', 
      click: () => { 
        if (mainWindow) { 
          mainWindow.webContents.send('open-dashboard');
          mainWindow.show(); 
          mainWindow.focus(); 
        } 
      } 
    },
    { type: 'separator' },
    { label: 'Quit', click: () => { app.quit(); } }
  ]);
  
  tray.setContextMenu(contextMenu);
  tray.on('click', () => {
    if (mainWindow) {
      mainWindow.webContents.send('open-dashboard');
      mainWindow.show();
      mainWindow.focus();
    }
  });

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

app.on('will-quit', () => {
  stopPythonBackend();
});
